/*
 * Copyright © 2022, Medelför OÜ. All rights reserved.
 * For any additional information refer to https://medelfor.com
 */

#ifndef MODULE_PROCESSOR_INCLUDE_UDOCS_PROCESSOR_VERSION_H_
#define MODULE_PROCESSOR_INCLUDE_UDOCS_PROCESSOR_VERSION_H_

#define VERSION_MAJOR 1
#define VERSION_MINOR 1
#define VERSION_INDEX 0
#define VERSION_TAG ""
#define VERSION_BUILD 52
#define VERSION_BUILD_ID "1f979682-7a62-48e2-9d54-3778808f1836"
#define VERSION_BUILD_TIMESTAMP 1688682693

#endif  // MODULE_PROCESSOR_INCLUDE_UDOCS_PROCESSOR_VERSION_H_
